app:
    resource: '@AppBundle/Controller/'
    type: annotation
    options:
      expose: true

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"